version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/src/backend/"
    schedule:
      interval: "weekly"
      day: "monday"
    allow:
      - dependency-type: "direct"
    assignees: []
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "deps(backend):"
    groups:
      data-science-dependencies:
        patterns:
          - "numpy"
          - "pandas"
          - "scikit-learn"
          - "xgboost"
          - "lightgbm"
          - "pandera"
          - "joblib"
      visualization-dependencies:
        patterns:
          - "matplotlib"
          - "seaborn"
          - "plotly"
      testing-dependencies:
        patterns:
          - "pytest*"
          - "mypy"
          - "black"
          - "isort"
    versioning-strategy: "auto"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "pip"
    directory: "/src/cli/"
    schedule:
      interval: "weekly"
      day: "monday"
    allow:
      - dependency-type: "direct"
    assignees: []
    labels:
      - "dependencies"
      - "cli"
    commit-message:
      prefix: "deps(cli):"
    versioning-strategy: "auto"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees: []
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "ci:"