name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'src/backend/docs/**'
      - 'docs/**'
      - '.github/workflows/deploy-docs.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/backend/docs/**'
      - 'docs/**'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-docs-${{ hashFiles('src/backend/requirements.txt', 'src/backend/docs/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-docs-

      - name: Install dependencies
        run: pip install -r src/backend/requirements.txt sphinx sphinx-rtd-theme sphinx-autodoc-typehints

      - name: Install backend package in development mode
        run: pip install -e src/backend

      - name: Generate API documentation
        run: cd src/backend/docs && sphinx-apidoc -f -o source/api ../src/backend

      - name: Build documentation
        run: cd src/backend/docs && make html

      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: src/backend/docs/_build/html

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download documentation
        uses: actions/download-artifact@v3
        with:
          name: documentation
          path: ./docs

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1